### ISSUE TITLE
'alien from [blank] rump joint'?

### ISSUE THREAD

**Issue by camtarn** [kikigame/Tinn#10]
I found an 'alien from  rump joint'. I'm guessing that blank should be filled with something?

![Untitled](https://user-images.githubusercontent.com/16687934/69277888-05b86200-0bd9-11ea-9ede-ac7e0a040ff7.png)

**Comment by kikigame** [comment]
No; it should just say "alien rump joint".

"Alien from " is the name of the alien monster type.

Each alien has a property to describe the world or ship that the alien is from, and that property is added to the species (monsterType) name.

Dead monsters and meat items (joints & steaks) have a reference to the species, but not the (late) monster. Thus, they don't reference the origin of the alien; it dies with the monster (but perhaps the truth is out there?).

Fix is to remove the word "from " from the species name and put in in the monster name() method.

Fixed in the next build.
