### ISSUE TITLE
BUG: unknown instruction rd to dig through without tools<!> Rock

### ISSUE THREAD

**Issue by camtarn** [kikigame/Tinn#3]
I think I ran into a wall, and/or a piano fell onto me.

Subsequently I got an oddly shortened screen with no @ for my character on it.

Moving restored the normal dungeon.

**Comment by camtarn** [comment]
![1](https://user-images.githubusercontent.com/16687934/69192807-3fc42e00-0b1d-11ea-9417-9b607442b465.png)
![2](https://user-images.githubusercontent.com/16687934/69192811-418df180-0b1d-11ea-9e25-12be7dbb2861.png)

**Comment by kikigame** [comment]
This is a genuine bug, and a race condition with the CGI script (cant/index.pl), not the core executable.

It seems to be caused by the browser sending a keystroke to the backend before it has finished reading the response of a previous keypress. Although there is locking code to prevent two threads accessing the backend at once, somehow the data through both connections becomes mangled, and data is interpreted as a thin-client instruction, raising an error.

Workaround is to press any valid key, then wait for the screen to redraw before pressing the next one.

**Comment by kikigame** [comment]
Fixed.

Hammering the input keys will no longer work; they are debounced by discarding any keys while an AJAX request is being processed.
This ensures that all server responses are processed in sequential order, so data cannot be mistaken for an instruction.
