### ISSUE TITLE
Alt doesn't work

### ISSUE THREAD

**Issue by camtarn** [kikigame/Tinn#5]
The Alt key doesn't work to force move onto traps. In particular, Alt+D selects the browser address bar.

(Chrome/Win)

**Comment by kikigame** [comment]
Any text referring to Alt refers to the console version of the game.

It's possible to add Javascript key listeners to alt-based key combinations, but not all of them can be used.

The Force button was added to the web interface to simulate the Alt button.

This may be fixable in JavaScript, but it's probably better to remove/rework the text referring to Alt, because it's fundamentally working with a different user interface paradigm.

**Comment by kikigame** [comment]
Binary will now use "Force" instead of "Alt/Meta" when using socket I/O rather than the terminal.

Fix pushed; text will be updated in the next build.
